from .dataset_config import *

DataConfig = {
    "PRETRAINING": [CC3M_595K, COCO_CAP, COCO_REG, COCO_REC],
    "PRETRAINING_sub": [COCO_CAP],

    "FINETUNING": [CONV_VideoChatGPT, VCG_HUMAN, VCG_PLUS_112K, CAPTION_VIDEOCHAT, CLASSIFICATION_K710, CLASSIFICATION_SSV2, CONV_VideoChat1, REASONING_NExTQA, REASONING_CLEVRER_QA, REASONING_CLEVRER_MC, VQA_WEBVID_QA],

    "VCGBench_FINETUNING": [CONV_VideoChatGPT, VCG_HUMAN, VCG_PLUS_112K, CAPTION_VIDEOCHAT, CONV_VideoChat1, VQA_WEBVID_QA],
    "MVBench_FINETUNING": [CLASSIFICATION_K710, CLASSIFICATION_SSV2, CONV_VideoChatGPT, REASONING_NExTQA, REASONING_CLEVRER_QA, REASONING_CLEVRER_MC, VQA_WEBVID_QA],
    "MVBench_capvqa": [CLASSIFICATION_K710_vqa, CLASSIFICATION_SSV2_vqa, CONV_VideoChatGPT_vqa, REASONING_NExTQA_vqa, REASONING_CLEVRER_QA_vqa, REASONING_CLEVRER_MC_vqa, VQA_WEBVID_QA_vqa],
    "MVBench_capvqa_tarsier": [CLASSIFICATION_K710_vqa_tarsier, CLASSIFICATION_SSV2_vqa_tarsier, CONV_VideoChatGPT_vqa_tarsier, REASONING_NExTQA_vqa_tarsier, REASONING_CLEVRER_QA_vqa_tarsier, REASONING_CLEVRER_MC_vqa_tarsier, VQA_WEBVID_QA_vqa_tarsier],
    "Total_vcap_tarsier": [CLASSIFICATION_K710_vqa_tarsier, CLASSIFICATION_SSV2_vqa_tarsier, CONV_VideoChatGPT_vqa_tarsier, REASONING_NExTQA_vqa_tarsier, REASONING_CLEVRER_QA_vqa_tarsier, REASONING_CLEVRER_MC_vqa_tarsier, VQA_WEBVID_QA_vqa_tarsier, CONV_VideoChat1_vqa_tarsier],
    "MVBench_capvqa_sub": [CLASSIFICATION_K710_vqa_sub, CLASSIFICATION_SSV2_vqa_sub, CONV_VideoChatGPT_vqa_sub, REASONING_NExTQA_vqa_sub, REASONING_CLEVRER_QA_vqa_sub, REASONING_CLEVRER_MC_vqa_sub, VQA_WEBVID_QA_vqa_sub],
    'cap_llavarecap':[CAP_LLAVARECAP],
    'VCGBench_capvqa':[CONV_VideoChatGPT_vqa, VCG_HUMAN_vqa, VCG_PLUS_112K_vqa, CAPTION_VIDEOCHAT_vqa, CONV_VideoChat1_vqa, VQA_WEBVID_QA_vqa],
    'Total_vcap':[CLASSIFICATION_K710_vqa, CLASSIFICATION_SSV2_vqa, CONV_VideoChatGPT_vqa, REASONING_NExTQA_vqa, REASONING_CLEVRER_QA_vqa, REASONING_CLEVRER_MC_vqa, VQA_WEBVID_QA_vqa, CONV_VideoChat1_vqa]
}
